mikepenz/multiplatform-markdown-renderer

build.gradle.kts
buildSrc/src/main/java/Dependencies.kt
gradle/wrapper/gradle-wrapper.properties

Compose 1.1.0-b02

---

build.gradle.kts
buildSrc/src/main/java/Dependencies.kt
gradle.properties
gradle/wrapper/gradle-wrapper.properties

dev -> main

---

gradle/wrapper/gradle-wrapper.properties

Update to gradle 7.3

---

build.gradle.kts
buildSrc/src/main/java/Dependencies.kt
gradle/wrapper/gradle-wrapper.properties

- upgrade to compose-jb 1.0.0-beta6-dev474 
- compose 1.1.0-beta03
- material 1.5.0-beta01

Upgrade dependencies (compose 1.1.0-beta03)

---

build.gradle.kts
buildSrc/src/main/java/Dependencies.kt
gradle/wrapper/gradle-wrapper.properties
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/Code.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/Markdown.kt

- specify Text colors as MaterialTheme.colors.onBackground to ensure compose-jb / compose-ui support
- currently integrating in a project with compose-jb would not properly handle the theme for Android

Enhanced text color theming

---

build.gradle.kts
compose-desktop/build.gradle.kts

- upgrade to compose-jb 1.0.0
- dokka 1.6.0 update
- aboutlibraries 10.0.0-b02

Upgrade to compose-jb 1.0.0

---

README.md
build.gradle.kts
compose-desktop/build.gradle.kts
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/Markdown.kt

- specify default modifier, simplify README

Update default modifier

---

README.md
build.gradle.kts
compose-desktop/build.gradle.kts
gradle/wrapper/gradle-wrapper.properties
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/Markdown.kt

Gradle 7.3.1

---

app/build.gradle.kts
build.gradle.kts
buildSrc/src/main/java/Dependencies.kt
gradle/wrapper/gradle-wrapper.properties
gradlew

- update compose versions to support Kotlin 1.6.10

Kotlin 1.6.10 support | Compose 1.1.0-rc2

---

multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/Extensions.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/Markdown.kt

- add support for nested bullet lists

Improve handling of nested bullet lists

---

multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/Code.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/Markdown.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/MarkdownDefaults.kt
multiplatform-markdown-renderer/src/jvmMain/kotlin/com/mikepenz/markdown/ImagePainterProvider.kt

- introduce new API to configure colors more flexible (Don't depend on MaterialTheme)
- REPLACES #26
- fix shadowing
-----
Thanks @raidzero for the initial proposal
Thanks @amank22 for additional input

Add support for custom text color

---

.github/workflows/ci.yml
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/Markdown.kt

- provide proper color and style to bullet and list
- FIX https://github.com/mikepenz/multiplatform-markdown-renderer/issues/42

Style unordered / ordered list with provided colors

---

README.md
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/Markdown.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/MarkdownCompositionLocals.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/MarkdownDefaults.kt

- introduce new bullet list handling (use circle ascii character by default)
- offer custom local handlers to adjust the behavior for ordered and unordered list
- FIX #41

Adjust bullet list styling

---

README.md
build.gradle.kts
buildSrc/src/main/java/Dependencies.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/Markdown.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/MarkdownCompositionLocals.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/MarkdownDefaults.kt

- dependency updates 
```
- dokka 1.6.21
- aboutLibs 10.2.0
- coil 2.1.0
- material 1.6.0
```

Dependency updates 2022.05.27

---

build.gradle.kts
buildSrc/src/main/java/Dependencies.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/Markdown.kt

- only attach a detectTapGestures if we have an URL 
- FIX #47

Only attach `detectTapGestures` if needed

---

build.gradle.kts
multiplatform-markdown-renderer/build.gradle.kts

- upgrade compose to 1.5.0-beta02

Compose 1.5.0-beta02

---

multiplatform-markdown-renderer/build.gradle.kts

Support for IOS simulator target

---

build.gradle.kts
buildSrc/src/main/java/Dependencies.kt
multiplatform-markdown-renderer/build.gradle.kts
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/MarkdownColors.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/utils/AnnotatedStringKtx.kt

- introduce ability to theme and color links 
- FIX #81

Add ability to color links

---

multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownHeader.kt

- introduce support for links and other annotated formats in headers
- FIX https://github.com/mikepenz/multiplatform-markdown-renderer/issues/78

Add ability to use links in headers

---

multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/Markdown.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/components/MarkdownComponents.kt

This is an updated branch with conflicts resolved based on: https://github.com/mikepenz/multiplatform-markdown-renderer/pull/58/
Thanks to @pbit

Allow to use custom components

---

multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownText.kt

- protect against illegal links not being openable

Protect against crash due to illegal link opening

---

README.md

- introduce documentation for custom components
- FIX https://github.com/mikepenz/multiplatform-markdown-renderer/issues/100

Expand documentation to explain custom components

---

multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/ComposeLocal.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/Markdown.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/components/MarkdownComponents.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownBlockQuote.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownCode.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownDivider.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownList.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/MarkdownColors.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/MarkdownDimens.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/MarkdownPadding.kt

- create `MarkdownDimens` to also offer ability to change some additional values
- expand `MarkdownPadding` with more options
- restructure some code

Introduce `MarkdownDimens` with new configurations | Introduce `DividerColor` setting | Offer additional `Padding` configurations

---

multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/ComposeLocal.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/Markdown.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/components/MarkdownComponents.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownBlockQuote.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownCode.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownDivider.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownList.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/MarkdownColors.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/MarkdownDimens.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/MarkdownPadding.kt

- make MarkdownBlockQuote fully customizable
- add support for nested MarkdownBlockQuote's

Introduce support for nested `MarkdownBlockQuotes`

---

.github/workflows/ci.yml

- update `ci` to actions
- use improved gradle cache action

Simplify CI setup

---

.github/workflows/ci.yml
build.gradle.kts
buildSrc/src/main/java/Dependencies.kt
gradle/wrapper/gradle-wrapper.properties

- upgrade compose to 1.6.0
- upgrade to kotlin 1.9.22

Upgrade Compose and Kotlin versions

---

.github/workflows/ci.yml
build.gradle.kts
buildSrc/src/main/java/Dependencies.kt
gradle/wrapper/gradle-wrapper.properties
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/Markdown.kt

Go beyond the second level of handling components

Recursive component handling

---

.github/workflows/ci.yml

- update actions to their latest releases

Update CI actions to newer versions

---

buildSrc/src/main/java/Dependencies.kt

- update to compose 1.6.6
- update to compose compiler 1.5.12
- update activity compose 1.9.0

Update to compose 1.6.6

---

multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/utils/AnnotatedStringKtx.kt

- skip whitespace for multiline blockquote
- FIX https://github.com/mikepenz/multiplatform-markdown-renderer/issues/112

Skip whitespace in multiline blockquote

---

.github/workflows/ci.yml

- move to new `uses: gradle/actions/setup-gradle@v3` from old `gradle/gradle-build-action@v3`

[CI] Update setup-gradle action

---

multiplatform-markdown-renderer/build.gradle.kts

- actually remove coil dependency in core

Remove coil dependency

---

.github/workflows/ci.yml
multiplatform-markdown-renderer-coil2/build.gradle.kts

- add the missing coil2/3 module deploy steps to CI

[CI] Add missing CI deploy steps

---

multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownText.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/utils/AnnotatedStringKtx.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/utils/Extensions.kt

- cleanup some code formatting
- expose TAGs for inline url and image handling

Small code cleanup

---

multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownCode.kt

- fix code not included if code block is not closed without a new line
- FIX https://github.com/mikepenz/multiplatform-markdown-renderer/issues/147

Fix code not included if code of code block is last line

---

app-desktop/build.gradle.kts
gradle/libs.versions.toml

- Fix sample desktop app image loading

Fix sample desktop app image loading

---

multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownText.kt

- rework click handling in paragraphs / text to only consume the click on the actual link and not the full component
- FIX https://github.com/mikepenz/multiplatform-markdown-renderer/issues/188

Rework link click detection

---

multiplatform-markdown-renderer-coil3/src/commonMain/kotlin/com/mikepenz/markdown/coil3/Coil3ImageTransformerImpl.kt

- simplify Coil3 intrinsic size logic
- relates to: https://github.com/mikepenz/multiplatform-markdown-renderer/issues/168#issuecomment-2321197857

Simplify Coil3 intrinsic size logic

---

README.md

Added example of changing the rendering of unordered list.
This resolves issue #216

Add example of custom component

---

multiplatform-markdown-renderer-m2/src/commonMain/kotlin/com/mikepenz/markdown/m2/MarkdownTypography.kt
multiplatform-markdown-renderer-m3/src/commonMain/kotlin/com/mikepenz/markdown/m3/MarkdownTypography.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/MarkdownTypography.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/utils/AnnotatedStringKtx.kt

- apply the defined code TextStyle to spannable strings

Fix TextStyle not applied to code in annotated strings

---

multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/utils/EntityConverter.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/utils/Extensions.kt

fix getUnescapedText error

---

multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownText.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/ImageTransformer.kt

- add ability to disable the animation for the placeholder via the ImageTransformer
- FIX #212

Add new ability to configure `PlaceholderConfig` to disable animation via the `ImageTransformer`

---

gradle.properties
multiplatform-markdown-renderer-code/build.gradle.kts
multiplatform-markdown-renderer-coil2/build.gradle.kts
multiplatform-markdown-renderer-coil3/build.gradle.kts
multiplatform-markdown-renderer-m2/build.gradle.kts
multiplatform-markdown-renderer-m3/build.gradle.kts
multiplatform-markdown-renderer/build.gradle.kts

- transition to new maven central portal publishing

[CI] New maven central publishing portal

---

multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/utils/AnnotatedStringKtx.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/utils/Extensions.kt

- make additional helpers visible for people overwriting internal string handling

Adjust visibility of some helper methods

---

gradle/build-logic/convention/src/main/kotlin/com/mikepenz/gradle/PublishingConventionPlugin.kt

- fix requirement to include sources

Fix publishing

---

app-desktop/build.gradle.kts
app/build.gradle.kts
app/gradle.properties
build.gradle.kts
gradle/libs.versions.toml
settings.gradle.kts

- upgrade convention plugion
- update version catalog
- cleanup

Upgrade build setup

---

.github/workflows/ci.yml
app/build.gradle.kts
gradle/libs.versions.toml

- rework sample app signing to be property based

Improve release signing logic

---

multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownTable.kt

- expose MarkdownTableHeader and MarkdownTableRow for simpler modification of their behavior
- FIX https://github.com/mikepenz/multiplatform-markdown-renderer/issues/285
Usage:
```
components = markdownComponents(
table = { it ->
MarkdownTable(
it.content, it.node, it.typography.text,
headerBlock = { content, header, tableWidth, style ->
MarkdownTableHeader(
content,
header,
tableWidth,
style,
maxLines = Int.MAX_VALUE
)
}, rowBlock = { content, header, tableWidth, style ->
MarkdownTableRow(
content,
header,
tableWidth,
style,
maxLines = Int.MAX_VALUE
)
}
)
}
),
```

Expose table row and header to offer more configuration flexibility on tables

---

build.gradle.kts
gradle/libs.versions.toml
settings.gradle.kts

- include convention plugin from version-catalog

Include convention plugin from version-catalog

---

multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/extendedspans/SquigglyUnderlineSpanPainter.kt

Fix import not failing in local build

---

gradle/libs.versions.toml

- update coil to latest 3.1.0 release

Update to Coil 3.1.0

---

multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/annotator/AnnotatedStringKtx.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/ComposeLocal.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownCode.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownDivider.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownList.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/utils/Extensions.kt

- add new API to map out auto links if we are already within a link. otherwise the second link overlaps the primary link causing issues
- FIX #277

Fix AUTOLINK in LINK causing issues

---

multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/annotator/AnnotatedStringKtx.kt

Change EOL handling from `\n` to a single space

---

MIGRATION.md

- introduce migration guides for v0.32.0 and v0.33.0

Introduce MIGRATION guide

---

.github/workflows/ci.yml

- use the proper module to bundle a release

Fix release sample app build

---

sample/shared/src/commonMain/kotlin/com/mikepenz/markdown/sample/MarkDownPage.kt

- adjust padding on sample to have it be within the scrollable container

Improve sample app padding

---

sample/android/build.gradle.kts
sample/desktop/build.gradle.kts
sample/desktop/src/jvmMain/kotlin/com/mikepenz/markdown/main.kt
sample/shared/build.gradle.kts
sample/shared/src/commonMain/kotlin/com/mikepenz/markdown/sample/LicensesPage.kt
sample/web/build.gradle.kts
settings.gradle.kts

- update to the latest version of AboutLibraries

Update AboutLibraries 

---

sample/web/src/commonMain/kotlin/com/mikepenz/markdown/Main.kt
settings.gradle.kts

- fix deprecation warning for aboutlibs in wasm sample

Fix sample deprecation warning from AboutLibs

---

.github/workflows/ci.yml
gradle.properties

- enable cross compilation for klibs

Publish using cross compilation

---

multiplatform-markdown-renderer-m2/src/main/AndroidManifest.xml
multiplatform-markdown-renderer-m3/src/main/AndroidManifest.xml
multiplatform-markdown-renderer/src/main/AndroidManifest.xml

```diff
diff --color=auto -r mikepenz-before/multiplatform-markdown-renderer/maven-metadata-local.xml mikepenz-after/multiplatform-markdown-renderer/maven-metadata-local.xml
11c11
<     <lastUpdated>20250419072910</lastUpdated>
---
>     <lastUpdated>20250419072637</lastUpdated>
diff --color=auto -r mikepenz-before/multiplatform-markdown-renderer-android/maven-metadata-local.xml mikepenz-after/multiplatform-markdown-renderer-android/maven-metadata-local.xml
11c11
<     <lastUpdated>20250419072906</lastUpdated>
---
>     <lastUpdated>20250419072633</lastUpdated>
diff --color=auto -r mikepenz-before/multiplatform-markdown-renderer-code/maven-metadata-local.xml mikepenz-after/multiplatform-markdown-renderer-code/maven-metadata-local.xml
11c11
<     <lastUpdated>20250419072917</lastUpdated> …
```

Remove unsued main source sets and AndroidManifest files

---

multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/Markdown.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/MarkdownImageState.kt

remove redundant variable reassignment for better readability and cleaner code
don't need test

Remove redundant variable reassignment for better readability and cleaner code

---

sample/web/src/commonMain/kotlin/com/mikepenz/markdown/Main.kt

Fix wasm example

---

multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/annotator/AnnotatedStringKtx.kt

add support for dollar token in markdown rendering
Fixes #446 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

add support for dollar token in markdown rendering

---

.github/workflows/ci.yml
gradle.properties

- Disable warnings as errors in Kotlin configuration

Disable warnings as errors in Kotlin configuration

---

multiplatform-markdown-renderer-code/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownHighlightedCode.kt
multiplatform-markdown-renderer-coil2/build.gradle.kts
multiplatform-markdown-renderer-coil3/build.gradle.kts
multiplatform-markdown-renderer/api/android/multiplatform-markdown-renderer.api
multiplatform-markdown-renderer/api/jvm/multiplatform-markdown-renderer.api
multiplatform-markdown-renderer/api/multiplatform-markdown-renderer.klib.api
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownTable.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownText.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/ImageTransformer.kt

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
Fixes # (issue)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

Code cleanup: remove deprecated code and unnecessary suppressions
