LICENSE
README.md
app/build.gradle.kts
build.gradle.kts
buildSrc/src/main/java/Dependencies.kt
compose-desktop/build.gradle.kts
gradle.properties
gradle/wrapper/gradle-wrapper.properties
gradlew
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/Code.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/Extensions.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/Markdown.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/MarkdownDefaults.kt
multiplatform-markdown-renderer/src/jvmMain/kotlin/com/mikepenz/markdown/ImagePainterProvider.kt

dev -> main

---

multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/Markdown.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/MarkdownDefaults.kt

- replace MaterialTheme with custom typography, possible to be overwritten with custom theme
- FIX https://github.com/mikepenz/multiplatform-markdown-renderer/issues/37

Offer ability to overwrite textStyle used in Markdown renderer

---

README.md
app/src/main/java/com/mikepenz/markdown/ui/MainActivity.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownCode.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownHeader.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownList.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownText.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/MarkdownColors.kt

THe refactor for 0.7.0, didn't actually use the the LocalContentColor where appropriate so text was always black. 
I also updated the README for the new style, added a code block to the sample app, and renamed the `backgroundCode` to `codeBackground` and added `codeText`

Fix regression, of configurable text and code colors

---

multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownCode.kt

- fix `IndexOutOfBounds` for illegal code block
- FIX https://github.com/mikepenz/multiplatform-markdown-renderer/issues/60

Protect against `IllegalOutOfBoundsException` for illegal code blocks

---

build.gradle.kts
buildSrc/src/main/java/Dependencies.kt
multiplatform-markdown-renderer/build.gradle.kts

- upgrade to compose 1.5.4
- upgrade to compose-mp 1.5.10
- upgrade to kotlin 1.9.20
- upgrade to coil 2.5.0
- upgrade to markdown 0.5.2

Upgrade to compose 1.5.4 | compose-mp 1.5.10 | Kotlin 1.9.20 | Markdown 0.5.2

---

build.gradle.kts
buildSrc/src/main/java/Dependencies.kt
multiplatform-markdown-renderer/build.gradle.kts
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/MarkdownColors.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/utils/AnnotatedStringKtx.kt

- set background to inline code (make it new config, so it can be defined as `Unspecified`)
- FIX #79

Add background for inline code blocks

---

app/src/main/java/com/mikepenz/markdown/ui/MainActivity.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/Markdown.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/components/MarkdownComponents.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownHeader.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/utils/AnnotatedStringKtx.kt

Added support for setext headers
```markdown
Title 1
======
Title 2
------
```
Also fixes a bug where whitespace is placed at the start of elements like ATX headers.

Added support for processing setext headers

---

app/src/main/java/com/mikepenz/markdown/ui/MainActivity.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownList.kt

In the current iteration of the app, if you do not have a surface wrapping the markdown element (like the current sample),  then numbers for ordered lists stay black.  
This PR adjusts it to color match the text, like the unordered bullets.  
I also updated the sample app with an in app switch between light and dark mode.

Fix Ordered List numbers not being color correct in dark mode

---

build.gradle.kts
buildSrc/src/main/java/Dependencies.kt

- update kotlin to 1.9.21
- update to markdown 0.6.0
- update composeCompiler to 1.5.5
- update to activityCompose 1.8.1

Update Dependencies | Kotlin 1.9.21 | markdown 0.6.0

---

multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/ComposeLocal.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownList.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/BulletHandler.kt

- expand `BulletHandler` to expose more information (index + type)
- adjust ordered list handling to always count up with a number
- Handle ordered lists (which are defined 1., 1., ...)
- FIX https://github.com/mikepenz/multiplatform-markdown-renderer/issues/89

Improve `BulletHandler` | Support unconventional ordered lists

---

README.md
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/Markdown.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/components/MarkdownComponents.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownBlockQuote.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownCode.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownHeader.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownImage.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownList.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownParagraph.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownText.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/utils/AnnotatedStringKtx.kt

- expose default Markdown components for easier use for custom components
- add Modifier to MarkdownParagraph forwarded to MarkdownText
- forward ColumnScope to MarkdownComponents to allow applying related Modifiers (like align)

Default components public | Forward `modifier` in `MarkdownParagraph` | Forward `ColumnScope` to `MarkdownComponents`

---

buildSrc/src/main/java/Dependencies.kt
multiplatform-markdown-renderer/build.gradle.kts
multiplatform-markdown-renderer/src/androidMain/kotlin/com/mikepenz/markdown/utils/ImagePainterProvider.kt

This should partially address #121
By default, coil does not support SVG images, instead trying to render them normally and failing.
Note that this isn't thoroughly tested but should work according to https://coil-kt.github.io/coil/svgs/

Add SVG support for images

---

buildSrc/src/main/java/Dependencies.kt
gradle.properties
multiplatform-markdown-renderer-m2/build.gradle.kts
multiplatform-markdown-renderer-m3/build.gradle.kts
multiplatform-markdown-renderer/build.gradle.kts
multiplatform-markdown-renderer/src/wasmJsMain/kotlin/com/mikepenz/markdown/utils/ImagePainterProvider.multiplatform-markdown-renderer.js.kt

- update to markdown library 0.7.0
- add the new wasm target
- FIX https://github.com/mikepenz/multiplatform-markdown-renderer/issues/55

Update to `jetbrains/markdown@0.7.0` | Add `wasmJs` target

---

multiplatform-markdown-renderer-m2/src/commonMain/kotlin/com/mikepenz/markdown/m2/MarkdownColors.kt
multiplatform-markdown-renderer-m3/src/commonMain/kotlin/com/mikepenz/markdown/m3/MarkdownColors.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/MarkdownColors.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/utils/AnnotatedStringKtx.kt

- introduce new API to pass `inlineCodeText` color differently from `codeText` color
- FIX https://github.com/mikepenz/multiplatform-markdown-renderer/issues/130

Offer new color option for `inlineCodeText`

---

compose-desktop/src/main/kotlin/main.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/utils/AnnotatedStringKtx.kt

- ensure the link can not be clicked after the link text itself ends due to a missed `pop()`
- relates to: https://github.com/mikepenz/multiplatform-markdown-renderer/pull/129

Fix text following a link is still clickable

---

multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownDivider.kt

- use the `dividerColor` for the `MarkdownDivider`
- FIX https://github.com/mikepenz/multiplatform-markdown-renderer/issues/131

Use the correct color for the `divider` 

---

multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/utils/AnnotatedStringKtx.kt

- add support for GFM strikethrough
- FIX https://github.com/mikepenz/multiplatform-markdown-renderer/issues/133

Include support for `GFMElementTypes.STRIKETHROUGH`

---

README.md
compose-desktop/src/main/kotlin/main.kt
multiplatform-markdown-renderer-m2/src/commonMain/kotlin/com/mikepenz/markdown/m2/Markdown.kt
multiplatform-markdown-renderer-m3/src/commonMain/kotlin/com/mikepenz/markdown/m3/Markdown.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/ComposeLocal.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/Markdown.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownParagraph.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownText.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/extendedspans/ExtendedSpanPainter.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/extendedspans/ExtendedSpans.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/extendedspans/RoundedCornerSpanPainter.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/extendedspans/SquigglyUnderlineSpanPainter.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/extendedspans/internal/ColorSerializers.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/extendedspans/internal/Lists.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/MarkdownExtendedSpans.kt

- introduce first draft of extended-spans by porting https://github.com/saket/extended-spans into this library
- Offer ability to define extended spans for the Markdown class used by the internal text component
This solves: https://github.com/mikepenz/multiplatform-markdown-renderer/issues/132
Thanks @saket for the great work on the `extended-spans` library.

Add support for `extended-spans` - Improved looks for inline code, animated underlines

---

README.md

Coil ~is not nice enough~ to mention this in their migration docs for v3. So, mention it here.

Add note about how to configure ImageLoader

---

multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/utils/AnnotatedStringKtx.kt

- ensure we only pop if we have a link annotation we set
- FIX https://github.com/mikepenz/multiplatform-markdown-renderer/issues/166

Fix crash with links not including a link

---

multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/ComposeLocal.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/Markdown.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/components/MarkdownComponents.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownList.kt

- add new feature to use the same custom markdown components in a bullet list via a `LocalMarkdownComponents` provider
- FIX https://github.com/mikepenz/multiplatform-markdown-renderer/issues/184

Ensure custom `MarkdownComponents` are also available to `Lists`

---

multiplatform-markdown-renderer-coil3/src/commonMain/kotlin/com/mikepenz/markdown/coil3/Coil3ImageTransformerImpl.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownImage.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownText.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/ImageTransformer.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/MarkdownImageState.kt

- move computation of placeholder size to ImageTransformer offering more flexibility
- add new PlaceholderConfig which contains the information on placeholder size and vertical align
- expand `ImageData` with `contentScale`, `alpha`, `colorFilter` allowing additional configuration options

Refactor `MarkdownImage` and `InlineImage` handling

---

multiplatform-markdown-renderer-m2/src/commonMain/kotlin/com/mikepenz/markdown/m2/MarkdownTypography.kt
multiplatform-markdown-renderer-m3/src/commonMain/kotlin/com/mikepenz/markdown/m3/MarkdownTypography.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/MarkdownTypography.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/utils/AnnotatedStringKtx.kt

make link text spanStyle configurable via the `MarkdownTypography` class this allows use to change it if they want change the fontWeight or text decoration.

Make links in text stylable via the MarkdownTypography class

---

app/src/screenshotTest/kotlin/com.mikepenz.markdown.ui/SnapshotTests.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/components/MarkdownComponents.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownImage.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownList.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/utils/AnnotatedStringKtx.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/utils/Extensions.kt

Currently leaf node text is not unescaped, even though it should be. For example the Markdown text `1\.` is incorrectly rendered with a backslash. The `HTMLGenerator` from the Intellij Markdown library is a good example where it is using `EntityConverter` to unescape this text. This PR adds unescaping using the same `EntityConverter` class.

Making use of EntityConverter to unescape text of leaf nodes

---

app/build.gradle.kts

- adjust minAPI to 24 for sample app
- Relates to: https://github.com/mikepenz/multiplatform-markdown-renderer/issues/223

Update sample app minSDK

---

multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownHeader.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownParagraph.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownText.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/utils/AnnotatedStringKtx.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/utils/EntityConverter.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/utils/Extensions.kt

- rework `AnnotatedString` extensions to no longer be composable functions, instead get the actual style passed in
- ensure we can use the string builders without compose available and offer the ability to build custom `Text` components benefitting from the markdown parsing and annotation capabilities
- deprecate prior composable functions

Introduce new API to build annotated markdown strings to be used in standard `Text` composables

---

README.md
multiplatform-markdown-renderer-m2/src/commonMain/kotlin/com/mikepenz/markdown/m2/Markdown.kt
multiplatform-markdown-renderer-m3/src/commonMain/kotlin/com/mikepenz/markdown/m3/Markdown.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/ComposeLocal.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/Markdown.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownText.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/ImageTransformer.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/MarkdownAnimations.kt

- add new API to configure animation on the `MarkdownText`
- This API allows modification of the animation, alternatively it's possible to disable animations
- FIX https://github.com/mikepenz/multiplatform-markdown-renderer/issues/244
```kotlin
Markdown(
content,
animations = markdownAnimations(
animateTextSize = { this /** No animation */ }
),
}
```

Replace API to disable animation for `MarkdownText`

---

README.md
app-desktop/build.gradle.kts
app-wasm/build.gradle.kts
app/build.gradle.kts
build.gradle.kts
gradle/libs.versions.toml
kotlin-js-store/yarn.lock
multiplatform-markdown-renderer-code/build.gradle.kts
multiplatform-markdown-renderer-coil2/build.gradle.kts
multiplatform-markdown-renderer-coil3/build.gradle.kts
multiplatform-markdown-renderer-m2/build.gradle.kts
multiplatform-markdown-renderer-m3/build.gradle.kts
multiplatform-markdown-renderer/build.gradle.kts

- upgrade to AGP 8.7.3 
- compose 1.7.6
- compose-multiplatform 1.7.3
- kotlin 2.1.0
- dokka 2.0.0
- aboutLib 11.3.0-rc02
- ktor 3.0.3
- upgrade to Kotlin 2.x language and api version

Upgrade to Kotlin 2.x | Compose Multiplatform 1.7.3

---

README.md

Remove the note about coil3 snapshots since it doesn't seem to be true anymore

Update README.md about coil3

---

multiplatform-markdown-renderer-code/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownHighlightedCode.kt

I noticed when playing around with this today that the code highlighting default definitions don't account for light and dark mode. With the default theme being darcula anything that is highlighted with the mark or code colors are basically illegible.
To solve this I added default theme to the definitions and added a helper function to check what mode we're in. I'm checking the luminance of the code background color to see if that's light or dark and applying that to the highlights theme.
Nothing major but I thought it might be a nice little quality of life improvement for default behavior to respect theme. Originally I made a change in `MarkdownHighlightedCode` without thinking too much about it then but then realized as soon as I put up the previous PR that it was a very wrong approach …

Update Code Highlights To Automatically Account For Dark Mode

---

multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/annotator/AnnotatedStringKtx.kt

- don't handle hard break as two new lines
- FIX https://github.com/mikepenz/multiplatform-markdown-renderer/issues/215

Adjust how HARD_LINE_BREAK is interpreted

---

multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/MarkdownImageState.kt

- retain legacy function's for `MarkdownImageState` to retain backwards compatibility

Enhance backwards compatiblity

---

multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/annotator/AnnotatedStringKtx.kt

- don't add a new line via EOL when there was a BR before
- FIX https://github.com/mikepenz/multiplatform-markdown-renderer/issues/301

Better handle BR and EOL occurrences

---

multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownHeader.kt

+ TalkBack will read out e.g. "This is an H3, heading" instead of "This is an H3".

Improve accessibility for MarkdownHeader.

---

multiplatform-markdown-renderer/api/android/multiplatform-markdown-renderer.api
multiplatform-markdown-renderer/api/jvm/multiplatform-markdown-renderer.api
multiplatform-markdown-renderer/api/multiplatform-markdown-renderer.klib.api
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/ComposeLocal.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownList.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/BulletHandler.kt

Allows for customizing the bullet based on the depth. Example usage:
```kt
Markdown(
MARKDOWN,
components = markdownComponents(
unorderedList = { ul ->
val markers = listOf("•", "◦", "▸", "▹")
CompositionLocalProvider(LocalBulletListHandler provides { _, _, _, level -> "${markers[level % markers.size]} " }) {
MarkdownBulletList(ul.content, ul.node, style = ul.typography.bullet)
}
}
)
)
```

Add depth to `BulletHandler`

---

multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownCode.kt

Avoid crashing when processing code frence without content.
Use the following markdown for testing
```md
```kotlin
```

Update code fence minimum child count logic

---

sample/web/src/commonMain/resources/index.html
sample/web/src/commonMain/resources/styles.css
sample/web/src/commonMain/resources/unsupported_browser.js

- Add viewport meta tag to `index.html`
- Migrate styles to `styles.css`
- Migrate error handling to `unsupported_browser.js`
Fixed the display of sample on mobile
| Before | After |
|--------|--------|
| ![Before](https://github.com/user-attachments/assets/28f1447f-2714-4bd2-af66-b65ea6dc87af) | ![After](https://github.com/user-attachments/assets/1f91312e-44cd-4543-9b41-2d427fa756f5) |

Add viewport meta tag to `index.html`

---

multiplatform-markdown-renderer-m2/src/commonMain/kotlin/com/mikepenz/markdown/m2/Markdown.kt
multiplatform-markdown-renderer-m3/src/commonMain/kotlin/com/mikepenz/markdown/m3/Markdown.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/LazyMarkdown.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/Markdown.kt

There is a logical duplication in handling nested elements between:
https://github.com/mikepenz/multiplatform-markdown-renderer/blob/d7c9c0dad54931ae42c6eec31fb041db8b3be460/multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/MarkdownExtension.kt#L76-L79
https://github.com/mikepenz/multiplatform-markdown-renderer/blob/d7c9c0dad54931ae42c6eec31fb041db8b3be460/multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/Markdown.kt#L178-L181

Remove nested handling of elements in `Markdown` and `LazyMarkdown`

---

.github/workflows/ci.yml

The runner was changed in https://github.com/mikepenz/multiplatform-markdown-renderer/commit/a2fb3c1c52129aa136e66c2b2874f9761e51419c but this condition wasn't updated, so now publications aren't running when a release is created.
Also seems like the `strategy` / `matrix` part could be removed entirely from the script now, with cross-compilation. You could also use a Linux-based runner instead of macOS if you prefer.

Fix publish step condition in CI workflow

---

README.md

Collecting with `Flow.collectAsStateWithLifecycle` will always first emit the initial value passed in, in this case, momentarily showing `State.Loading` again every time the collection restarts.
Using `StateFlow.collectAsStateWithLifecycle` instead avoids this problem, as its initial value will be the current `value` of the `StateFlow`, which can already be `State.Success` if the parsing was completed earlier.

Fix VM example in README

---

multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/model/MarkdownState.kt
sample/android/src/screenshotTest/kotlin/com/mikepenz/markdown/ui/m2/util/Helper.kt
sample/android/src/screenshotTest/kotlin/com/mikepenz/markdown/ui/m3/util/Helper.kt

- make `rememberMarkdownState` `immediate` if we are in `LocalInspectionMode` (e.g. preview)
- FIX https://github.com/mikepenz/multiplatform-markdown-renderer/issues/385

Make markdown parsing `immediate` if `LocalInspectionMode` is true

---

build.gradle.kts
sample/shared/build.gradle.kts
sample/web/src/commonMain/resources/load.mjs
settings.gradle.kts

Use `compatPatrouille`

---

multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownCode.kt
multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownText.kt

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
Fixes # (issue)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

Cleanup code

---

multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/components/MarkdownComponents.kt

- fix stability for markdown components
Fixes # (issue)

Also make markdown components stable

---

multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/compose/elements/MarkdownList.kt

+ TalkBack will read out e.g. "One, lorem ipsum" instead of "One" for the ordered list item prefix number and then "lorem ipsum" on its own.
+ TalkBack selects both the item prefix and the text as one element:
+ Does not apply to list items which prepend a checkbox.
---
Relates #417, #318

Improve accessibility of ordered and unordered list items.
